-- CREATE DATABASE wp_db;
-- CREATE USER 'skang'@'%' IDENTIFIED BY 'skang';
-- GRANT ALL PRIVILEGES ON wp_bd.sql TO 'skang'@'%';
-- FLUSH PRIVILEGES;
CREATE DATABASE wp_db;
GRANT ALL PRIVILEGES ON *.* TO 'skang'@'%' IDENTIFIED BY 'skang' WITH GRANT OPTION;
FLUSH PRIVILEGES;
